region: ap-southeast-1

function_name: tweetindex-streamer
handler: service.handler
role: service-role/tweetindex
description: RESTful API for stock tweets from Twitter's Streaming API

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id:
aws_secret_access_key:

dist_directory: dist
timeout: 15
memory_size: 128
